### ISSUE TITLE
Example Grafana Dashboard / AlertManager Rules

### ISSUE THREAD

**Issue by AlexDaichendt** [kadalu/gluster-metrics-exporter#37]
Hey!

I'm sure this exporter was deployed by some people; does anyone have a pretty Grafana dashboard? 
Furthermore, maybe someone could share their AlertManager rules. 

I'm sure more people would love to have a basis to build upon.

**Comment by foi** [comment]
There are rules I use
```
name: GlusterVolumeVolumeNameIsNotStarted
expr: glusterfs_volume_brick_count{name="volume_name",state!="Started",type="Replicate"}
for: 30s
labels:
  severity: critical
annotations:
  summary: Gluster volume volume_name is not started (instance {{ $labels.instance }})
  
name: GlusterMissingBickInVolumeVolumeName
expr: glusterfs_subvol_up_bricks{subvol_index="0",volume_name="volume_name",volume_state="Started",volume_type="Replicate"} != 3
for: 30s
labels:
  severity: critical
annotations:
  summary: Some bricks are missing for volume_name (instance {{ $labels.instance }})
```
